### ISSUE TITLE
npm run install-all doesn't work

### ISSUE THREAD

**Issue by RobertoUa** [shockone/black-screen#1]
npm-debug.log
```javascript
0 info it worked if it ends with ok
1 verbose cli [ '/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/iojs',
1 verbose cli   '/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'install-all' ]
2 info using npm@2.8.3
3 info using node@v1.8.1
4 verbose run-script [ 'preinstall-all', 'install-all', 'postinstall-all' ]
5 info preinstall-all black-screen@0.0.1
6 info install-all black-screen@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info black-screen@0.0.1 Failed to exec install-all script
9 verbose stack Error: black-screen@0.0.1 install-all: `npm install && npm run install-native && npm run cleanup`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/roberto/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:169:7)
9 verbose stack     at ChildProcess.<anonymous> (/Users/roberto/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:169:7)
9 verbose stack     at maybeClose (child_process.js:953:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
10 verbose pkgid black-screen@0.0.1
11 verbose cwd /Users/roberto/workspace/black-screen
12 error Darwin 14.3.0
13 error argv "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/npm" "run" "install-all"
14 error node v1.8.1
15 error npm  v2.8.3
16 error code ELIFECYCLE
17 error black-screen@0.0.1 install-all: `npm install && npm run install-native && npm run cleanup`
17 error Exit status 1
18 error Failed at the black-screen@0.0.1 install-all script 'npm install && npm run install-native && npm run cleanup'.
18 error This is most likely a problem with the black-screen package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm install && npm run install-native && npm run cleanup
18 error You can get their info via:
18 error     npm owner ls black-screen
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by RobertoUa** [comment]
I use iojs 1.8.1

**Comment by RobertoUa** [comment]
```
> pty.js@0.2.7-1 install /Users/roberto/workspace/black-screen/node_modules/pty.js
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/roberto/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/roberto/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/request/request.js:1156:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:412:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:302:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/roberto/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/roberto/workspace/black-screen/node_modules/pty.js
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/npm" "install" "pty.js"
npm ERR! node v1.8.1
npm ERR! npm  v2.8.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/roberto/workspace/black-screen/npm-debug.log

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/npm" "run" "install-native"
npm ERR! node v1.8.1
npm ERR! npm  v2.8.3
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 install-native: `npm_config_disturl=https://atom.io/download/electron npm_config_target=0.23.0 npm_config_arch=x64 HOME=~/.electron-gyp npm install 'pty.js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 install-native script 'npm_config_disturl=https://atom.io/download/electron npm_config_target=0.23.0 npm_config_arch=x64 HOME=~/.electron-gyp npm install 'pty.js''.
npm ERR! This is most likely a problem with the black-screen package,```

**Comment by shockone** [comment]
@RobertoUa could you pull and try again, please?

**Comment by RobertoUa** [comment]
```javascript
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/roberto/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/roberto/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/request/request.js:1156:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:412:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:302:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/roberto/.nvm/versions/io.js/v1.8.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/roberto/workspace/black-screen/node_modules/pty.js
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/roberto/.nvm/versions/io.js/v1.8.1/bin/npm" "install" "pty.js"
npm ERR! node v1.8.1
npm ERR! npm  v2.8.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by shockone** [comment]
@RobertoUa, what commands you ran? It should be 

```
git pull
npm run install-all
```

**Comment by RobertoUa** [comment]
yes

**Comment by aCarpenter** [comment]
I hate to reopen this issue but I'm having a similar problem:
`npm ERR! node v0.10.9
npm ERR! npm  v2.7.3

npm ERR! missing script: install-all
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

I just pulled, and I'm in the root of the cloned repo. Is there some dependency I'm missing?

**Comment by RobertoUa** [comment]
Can you please update node to latest version?

**Comment by shockone** [comment]
@aCarpenter, also, you need to use `npm install` instead of `npm run install-all` with the latest version.
