### ISSUE TITLE
Failed to start in linux

### ISSUE THREAD

**Issue by scampi** [shockone/black-screen#208]
`npm install` runs with no error, but when running `npm start` I get the following:

```
> black-screen@0.0.1 start /home/yfful/documents/black-screen
> gulp

[22:21:59] Requiring external module babel-core/register
[22:22:00] Using gulpfile ~/documents/black-screen/gulpfile.babel.js
[22:22:00] Starting 'default'...
[22:22:00] Starting 'watch'...
[22:22:00] Starting 'clean'...
[22:22:00] Finished 'clean' after 55 ms
[22:22:00] Starting 'typescript'...
[22:22:00] Starting 'sass'...
[22:22:01] Starting 'copy-html'...
[22:22:01] Finished 'default' after 185 ms
[22:22:01] Finished 'copy-html' after 64 ms
[22:22:01] gulp-notify: [Black Screen Watcher] SCSS has been compiled.
[22:22:01] Finished 'sass' after 367 ms
[22:22:06] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
[22:22:06] Finished 'typescript' after 5.13 s
[22:22:06] Starting 'build'...
[22:22:06] Finished 'build' after 12 μs
[22:22:06] Finished 'watch' after 5.23 s
App threw an error when running [TypeError: Cannot read property 'setIcon' of undefined]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'setIcon' of undefined
    at Object.<anonymous> (/home/yfful/documents/black-screen/compiled/src/main/Main.js:41:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/home/yfful/documents/black-screen/node_modules/electron-prebuilt/dist/resources/default_app/main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

Some system information. I don't know what node version should be used though.

```
❯ npm -v
2.14.15
❯ node -v
v4.2.4
```

**Comment by shockone** [comment]
Sorry, Linux is not supported at the moment.

**Comment by shockone** [comment]
This issue is fixed now.
