### ISSUE TITLE
"TypeError: undefined is not a function" in typescript lib.

### ISSUE THREAD

**Issue by Kobold** [shockone/black-screen#21]
I get this error on mac os 10.10.5, npm 2.14.2, node v0.12.7.

black-screen version 7b11841a50c4dcde25ad4c9c8b24ad918e2b7878.

```sh
$ npm run install-all
...
# No errors.

$ gulp
[17:35:09] Using gulpfile ~/black-screen/gulpfile.js
[17:35:09] Starting 'default'...
[17:35:09] Starting 'watch'...
[17:35:09] Starting 'clean'...
[17:35:09] Finished 'default' after 359 ms
[17:35:09] Finished 'clean' after 58 ms
[17:35:09] Starting 'typescript'...
[17:35:09] Starting 'sass'...
[17:35:10] Starting 'react'...
[17:35:11] gulp-notify: [Black Screen Watcher] React has been compiled.
[17:35:11] Finished 'react' after 1.83 s
/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35171
            if (host.fileExists(fileName)) {
                     ^
TypeError: undefined is not a function
    at tryLoad (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35171:22)
    at loadNodeModuleFromFile (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35164:20)
    at loadModuleFromNodeModules (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35213:30)
    at nodeModuleNameResolver (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35158:20)
    at resolveModuleName (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35140:41)
    at /Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35417:113
    at Object.map (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:945:29)
    at resolveModuleNamesWorker (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35417:65)
    at processImportedModules (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35833:35)
    at findSourceFile (/Users/agkish/black-screen/node_modules/typescript/lib/typescript.js:35795:21)
```

**Comment by ncerminara** [comment]
+1

**Comment by ibrahima** [comment]
Possibly related to https://github.com/Microsoft/TypeScript/issues/4565

**Comment by niedzielski** [comment]
Same issue on Linux Mint 17.2.

**Comment by shanahanjrs** [comment]
Getting same issue, also on osx 10.10.5

**Comment by ibrahima** [comment]
See my pull request #22 for a possible fix, but I get a few more errors after fixing this one and I don't know how to deal with ES6/Typescript/Node issues.

**Comment by geolado** [comment]
Same here

**Comment by mason505** [comment]
Same here. OS X 10.10.5

**Comment by jjbandit** [comment]
Same here: Arch 4.1.6-1

**Comment by Talamantez** [comment]
Same on Ubuntu 14.04

**Comment by sapanbhuta** [comment]
Same here. OS X 10.10.5

**Comment by niedzielski** [comment]
@ibrahima, I tried your fork and it indeed runs (well done!). Unfortunately, I can't figure out how to bring up a prompt. There's no prompt or text on the screen. This might be a high DPI Linux only issue.

**Comment by kirankgollakota** [comment]
@ibrahima i tried installing from your PR and it looks like what's happening is an issue with import paths: https://github.com/shockone/black-screen/blob/00974e9aa944048983968036c1f881dc24acddbb/views/main.js#L4.

this should probably be a relative path. i'll submit a PR for this.

**Comment by ncerminara** [comment]
Confirming that @ibrahima's fork https://github.com/ibrahima/black-screen works if you update `views/main.js`.

Everything's pretty solid. Love the interface. Kind of slow, but was expecting that.

**Comment by ChrisAldama** [comment]
Same error
Archlinux

**Comment by jimmyhmiller** [comment]
@kirankgollakota Just submitted a PR for the same issue. #25

**Comment by kirankgollakota** [comment]
@jimmyhmiller nice. turns out good things happen when you take a break for pizza :)

**Comment by foi** [comment]
same error 
```
Linux crunchbangplusplus 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

elixir@crunchbangplusplus:~/black-screen$ gulp -v
[11:17:19] CLI version 3.9.0
[11:17:19] Local version 3.9.0

elixir@crunchbangplusplus:~/black-screen$ node -v
v0.10.40
```

**Comment by jamesob** [comment]
+1
```
 $ npm --version

1.3.10
                                                                                                                                      
 $ cat /etc/lsb-release 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```

**Comment by Star-Lord-XIII** [comment]
`npm install gulp-typescript` seems to resolve the issue.

**Comment by Fzzr** [comment]
+1 to this issue and can confirm @Star-Lord-XIII 's fix

**Comment by OmgImAlexis** [comment]
@Star-Lord-XIII's fix works.

````
➜  black-screen git:(master) iojs --version             
v2.3.3
➜  black-screen git:(master) sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46
````

**Comment by samet** [comment]
OmgImAlexis+1. I'm in exact same state.

**Comment by ilianaza** [comment]
+1 I get the same error:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27

$gulp
...
[4667:0906/001730:INFO:CONSOLE(336)] "Uncaught Error: Cannot find module '/Users/me/dev/black-screen/compiled/src/views/TerminalLayout'", source: module.js (336)

```

**Comment by Thr1ve** [comment]
@ilianaza @samet @OmgImAlexis see #25 as already mentioned by @jimmyhmiller above

**Comment by shockone** [comment]
Fixed with help of @ibrahima and others. Thank you, guys.

**Comment by Kobold** [comment]
Thank you for the cool terminal!
