### ISSUE TITLE
Unable to run / bundle on linux

### ISSUE THREAD

**Issue by hickscorp** [shockone/black-screen#210]
Using the master branch on commit 08afd4e, the following commands yield errors:

```
npm run package

> black-screen@0.0.1 package /home/doodloo/black-screen
> gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns' --asar=true

[15:17:00] Requiring external module babel-core/register
[15:17:01] Using gulpfile ~/black-screen/gulpfile.babel.js
[15:17:01] Starting 'typescript'...
[15:17:02] Starting 'sass'...
[15:17:02] Starting 'copy-html'...
[15:17:02] Finished 'copy-html' after 50 ms
[15:17:02] gulp-notify: [Black Screen Watcher] SCSS has been compiled.
[15:17:02] Finished 'sass' after 863 ms
[15:17:06] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
[15:17:06] Finished 'typescript' after 4.47 s
[15:17:06] Starting 'build'...
[15:17:06] Finished 'build' after 14 μs
Downloading electron-v0.36.7-darwin-x64.zip
[============================================>] 100.0% of 39.52 MB (1.36 MB/s)
Packaging app for platform darwin x64 using electron v0.36.7
EACCES: permission denied, mkdir '/Applications'

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/doodloo/.nvm/versions/node/v5.3.0/bin/node" "/home/doodloo/.nvm/versions/node/v5.3.0/bin/npm" "run" "package"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 package: `gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns' --asar=true`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 package script 'gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns' --asar=true'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns' --asar=true
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/doodloo/black-screen/npm-debug.log
```

Okay, the compilation is trying to build for MacOSX.
But simply trying to start the app also yields errors:

```
npm start

> black-screen@0.0.1 start /home/doodloo/black-screen
> gulp

[15:20:03] Requiring external module babel-core/register
[15:20:03] Using gulpfile ~/black-screen/gulpfile.babel.js
[15:20:03] Starting 'default'...
[15:20:03] Starting 'watch'...
[15:20:03] Starting 'clean'...
[15:20:03] Finished 'clean' after 27 ms
[15:20:03] Starting 'typescript'...
[15:20:03] Starting 'sass'...
[15:20:03] Starting 'copy-html'...
[15:20:03] Finished 'default' after 109 ms
[15:20:03] Finished 'copy-html' after 46 ms
[15:20:03] gulp-notify: [Black Screen Watcher] SCSS has been compiled.
[15:20:03] Finished 'sass' after 269 ms
[15:20:07] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
[15:20:07] Finished 'typescript' after 3.62 s
[15:20:07] Starting 'build'...
[15:20:07] Finished 'build' after 3.17 μs
[15:20:07] Finished 'watch' after 3.68 s
App threw an error when running [TypeError: Cannot read property 'setIcon' of undefined]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'setIcon' of undefined
    at Object.<anonymous> (/home/doodloo/black-screen/compiled/src/main/Main.js:41:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/home/doodloo/black-screen/node_modules/electron-prebuilt/dist/resources/default_app/main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by shockone** [comment]
Hi, @hickscorp. Unfortunately, Linux is not supported at the moment. It will be after the 1.0 release.

**Comment by hickscorp** [comment]
Hi and thanks for the answer @shockone!

**Comment by shockone** [comment]
This issue is fixed now.

**Comment by hickscorp** [comment]
@shockone whaaaaat!? Awesome! :+1: :100: Testing right away.
