### ISSUE TITLE
Application not starting in Ubuntu 14.04

### ISSUE THREAD

**Issue by mkenne11** [shockone/black-screen#228]
I attempted to run black-screen on Ubuntu 14.04 (64 bit) however it failed to start. I read in the readme file that Linux is currently not supported - however I thought I'd ask for assistance in case the issue is easy to remedy.

The application build (using 'npm i') went fine. When attempting to start the app I received a "Uncaught Exception: TypeError: Cannot read property 'setIcon' of undefined".  Any ideas?

See output when running "npm start" below.

> \>black-screen@0.0.1 start /home/user1/black-screen
>  \>gulp
>
[06:09:39] Requiring external module babel-core/register
[06:09:44] Using gulpfile ~/black-screen/gulpfile.babel.js
[06:09:44] Starting 'default'...
[06:09:44] Starting 'watch'...
[06:09:44] Starting 'clean'...
[06:09:45] Finished 'clean' after 194 ms
[06:09:45] Starting 'typescript'...
[06:09:45] Starting 'sass'...
[06:09:45] Starting 'copy-html'...
[06:09:45] Finished 'default' after 932 ms
[06:09:46] Finished 'copy-html' after 409 ms
[06:09:47] gulp-notify: [Black Screen Watcher] SCSS has been compiled.
[06:09:47] Finished 'sass' after 1.83 s
[06:10:08] gulp-notify: [Black Screen Watcher] TypeScript has been compiled.
[06:10:08] Finished 'typescript' after 24 s
[06:10:08] Starting 'build'...
[06:10:08] Finished 'build' after 43 μs
[06:10:09] Finished 'watch' after 24 s
>
**App threw an error when running [TypeError: Cannot read property 'setIcon' of undefined]**
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'setIcon' of undefined
    at Object.<anonymous> (/home/user1/black-screen/compiled/src/main/Main.js:12:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/home/user1/black-screen/node_modules/electron-prebuilt/dist/resources/default_app/main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)`

**Comment by shockone** [comment]
Sorry, Linux is not supported at the moment.

**Comment by shockone** [comment]
This issue is fixed now.

**Comment by mkenne11** [comment]
Thanks very for that! I was able to get it working on Ubuntu with yesterdays version of the "master" branch.

There two problems I had
- Node.js wasn't setup properly (I'm a node newbie), and
- I commented out references to app.dock.

Your solution is definitely more elegant :)

**Comment by mkenne11** [comment]
Btw. I just cloned the latest "master" branch and can confirm it's working on my Ubuntu machine :)

**Comment by shockone** [comment]
Thank you, @mkenne11.
