### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by dflock** [shockone/black-screen#245]
Just tried installing black-screen on linux and got this error on startup:

```console
$ git clone https://github.com/shockone/black-screen.git && cd black-screen
$ npm i
$ npm start

> black-screen@0.0.1 start /home/duncan/bin/black-screen
> gulp

[14:50:17] Requiring external module babel-core/register
/home/duncan/bin/black-screen/gulpfile.babel.js:5
const gulp = require("gulp");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (/home/duncan/bin/black-screen/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/duncan/bin/black-screen/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/home/duncan/bin/black-screen/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/duncan/bin/black-screen/node_modules/gulp/node_modules/liftoff/index.js:192:16)

npm ERR! Linux 3.11.0-26-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.10
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 start script 'gulp'.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/duncan/bin/black-screen/npm-debug.log
```

I've included the output of the `npm -i` command and the /npm-debug.log file in the .zip file attached to this issue: [black-screen-debug.zip](https://github.com/shockone/black-screen/files/137110/black-screen-debug.zip)

### System Info:

```console
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 13.10
Release:	13.10
Codename:	saucy

$ uname -a
Linux duncan-desktop 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ npm --version
2.14.9

$ nodejs --version
v0.12.10

```

**Comment by mike-koch** [comment]
I had the same issue.  Updating node to v5.6.0 (and npm to 3.6.0) fixed the issue. I also had to run `npm rebuild node-sass` to fix an issue with `sass` in order to get it running.

**Comment by owennewo** [comment]
I had the same issue.  

My initial error was 
`SyntaxError: Use of const in strict mode.`

The fix for the above error is:

down vote
If this is happening in nodejs, it is due to the older version of nodejs. Update node by using,

```
1) Clear NPM's cache:

sudo npm cache clean -f
2) Install a little helper called 'n'

sudo npm install -g n
3) Install latest stable NodeJS version
sudo n stable
```

After this I got another cryptic error:
```
            fn.apply(this, arguments);
               ^
TypeError: fn.apply is not a function
```

Typing gulp revealed what the problem was and as mike-koch has already said the fix is 
`npm rebuild node-sass`

The console now starts and works for me.

**Comment by FlamesoFF** [comment]
Same problem here.

> npm install -g n
Not working.

> npm ERR! notsup Not compatible with your operating system or architecture: n@2.1.1

**Comment by seothuang** [comment]
I am new to Node and am trying to install gulp but received the following error and have not been successful in solving it for more then 2 weeks, can someone help please?

D:\conFusion\node_modules\gulp-imagemin\index.js:2
const path = require('path');

SyntaxError: Use of const in strict mode.
   at Module._compile (module.js:439:2)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (D:\conFusion\gulpfile.js:7:16)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
