### ISSUE TITLE
Linux: Can't execute any commands

### ISSUE THREAD

**Issue by philer** [shockone/black-screen#268]
Hi there, I saw the various comments about Linux not being supported (yet) but then you do seem to take care of some of the bugs so I'll just submit one and hope for the best. :)

The terminal starts fine. The autocomplete also shows all the correct things (very sexy) but then once I hit enter nothing happens except for a little waiting animation. Meanwhile the terminal from which I ran black-screen spits out the following error:

```
TypeError: Cannot read property 'split' of undefined
    at Object.baseName (/****/black-screen/compiled/src/Utils.js:157:13)
    at Object.<anonymous> (/****/black-screen/compiled/src/PTYInternal.js:13:71)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1007:3
/****/black-screen/compiled/src/Utils.js:157
    if (path.split(Path.sep).length === 1) {
```
This happens for any command I run (I tried `ls`, `htop`, `cat`).
However `cd` works and after running `cd` the error *sometimes* no longer appears and black-screen instead just claims 'command "..." not found.' for anything I run.

**Comment by verzil** [comment]
how did you get it working? when i run it on arch it just blacks out.
