### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by ninjaprawn** [shockone/black-screen#291]
Just a quick note: I understand everyone has different setups, but if we could have something which says "using Node vX" or any other steps that have been performed with node, that might save some people time when trying to compile this project.

Error Report:

OS Version: Mac OS X 10.11.3

Node version: 5.0.0

Log:
```
Georges-MacBook-Pro:black-screen ninja$ npm i
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> black-screen@0.0.1 preinstall /Volumes/Files/Developer/black-screen
> npm prune


> black-screen@0.0.1 postinstall /Volumes/Files/Developer/black-screen
> npm run recompile


> black-screen@0.0.1 recompile /Volumes/Files/Developer/black-screen
> HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$npm_package_electronVersion --arch=x64 --dist-url=https://atom.io/download/atom-shell

sh: line 0: cd: node_modules/pty.js: No such file or directory
gyp: binding.gyp not found (cwd: /Volumes/Files/Developer/black-screen) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--target=0.37.7" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /Volumes/Files/Developer/black-screen
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "run" "recompile"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 recompile: `HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$npm_package_electronVersion --arch=x64 --dist-url=https://atom.io/download/atom-shell`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 recompile script 'HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$npm_package_electronVersion --arch=x64 --dist-url=https://atom.io/download/atom-shell'.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$npm_package_electronVersion --arch=x64 --dist-url=https://atom.io/download/atom-shell
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Files/Developer/black-screen/npm-debug.log

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 postinstall: `npm run recompile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 postinstall script 'npm run recompile'.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run recompile
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Files/Developer/black-screen/npm-debug.log
```

Log file: http://ninjaprawn.com/black-screen-npm-debug.log

**Comment by ninjaprawn** [comment]
If someone could post the result of `echo $NODE_PATH`, that would be great.

**Comment by ninjaprawn** [comment]
Using the LTS version from Node's website fixed this problem
