### ISSUE TITLE
Can not start the app

### ISSUE THREAD

**Issue by polinom** [shockone/black-screen#316]
Was following instalation guid in **README.md**

```
git clone https://github.com/shockone/black-screen.git && cd black-screen
npm i
npm start
```
Receive following exception:

```
> black-screen@0.0.1 start /Users/igor/wp/black-screen
> gulp

[09:35:45] Using gulpfile ~/wp/black-screen/gulpfile.js
[09:35:45] Starting 'default'...
[09:35:45] Starting 'watch'...
[09:35:45] Starting 'clean'...
[09:35:45] Finished 'clean' after 60 ms
[09:35:45] Starting 'typescript'...
[09:35:45] Starting 'sass'...
[09:35:45] 'sass' errored after 53 ms
[09:35:45] Error: dlopen(/Users/igor/wp/black-screen/node_modules/node-sass/vendor/darwin-x64-47/binding.node, 1): no suitable image found.  Did find:
	/Users/igor/wp/black-screen/node_modules/node-sass/vendor/darwin-x64-47/binding.node: truncated mach-o error: segment __LINKEDIT extends to 2602136 which is past end of file 1879600
    at Error (native)
    at Object.Module._extensions..node (module.js:423:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/igor/wp/black-screen/node_modules/node-sass/lib/index.js:23:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
[09:35:45] Finished 'watch' after 201 ms
[09:35:45] Starting 'copy-html'...
[09:35:45] Finished 'default' after 206 ms
[09:35:46] Finished 'copy-html' after 32 ms

> black-screen@0.0.1 tsc /Users/igor/wp/black-screen
> tsc


> black-screen@0.0.1 electron /Users/igor/wp/black-screen
> electron .

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/igor/wp/black-screen/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/Users/igor/wp/black-screen/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/igor/wp/black-screen/node_modules/.bin/npm" "run" "electron"
npm ERR! node v5.3.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 electron: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 electron script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/igor/wp/black-screen/npm-debug.log
/Users/igor/wp/black-screen/node_modules/gulp-shell/node_modules/async/lib/async.js:52
            fn.apply(this, arguments);
               ^

TypeError: fn.apply is not a function
    at /Users/igor/wp/black-screen/node_modules/gulp-shell/node_modules/async/lib/async.js:52:16
    at /Users/igor/wp/black-screen/node_modules/gulp-shell/node_modules/async/lib/async.js:264:21
    at /Users/igor/wp/black-screen/node_modules/gulp-shell/node_modules/async/lib/async.js:44:16
    at /Users/igor/wp/black-screen/node_modules/gulp-shell/index.js:75:7
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/igor/wp/black-screen/npm-debug.log

```

**Comment by shockone** [comment]
Did `npm i` end successfully? Can you pull the latest master, remove the `node_modules` directory and try again?

**Comment by polinom** [comment]
Thanks @shockone. You ware right. I had to reinstall it... after it started successfully. However, when I enter `pwd` command it freezes. I should probably create a separate issue for this?

**Comment by shockone** [comment]
Yes, please, @polinom. Perhaps you mean that it freezes if you type `pwd` right after the app is loaded. If you wait a few seconds and then type, it should work fine. But it's still a bug.
