### ISSUE TITLE
Not installing on Linux Mint 17.3 (Ubuntu 14.04 LTS)

### ISSUE THREAD

**Issue by rv816** [shockone/black-screen#368]
node version 6.2
npm version 3.9

Here is log.
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.9.2
3 info using node@v6.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle black-screen@0.0.1~prestart: black-screen@0.0.1
6 silly lifecycle black-screen@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle black-screen@0.0.1~start: black-screen@0.0.1
8 verbose lifecycle black-screen@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle black-screen@0.0.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ryan/local/black-screen/node_modules/.bin:/usr/bin:/home/ryan/PostgreSQL/9.5/bin:/home/ryan/pypy-5.1.1-linux64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ryan/anaconda3/bin:/home/ryan/cloned/pyscreen/copysc/:/home/ryan/local/bin
10 verbose lifecycle black-screen@0.0.1~start: CWD: /home/ryan/local/black-screen
11 silly lifecycle black-screen@0.0.1~start: Args: [ '-c',
11 silly lifecycle   'npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron' ]
12 silly lifecycle black-screen@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle black-screen@0.0.1~start: Failed to exec start script
14 verbose stack Error: black-screen@0.0.1 start: `npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid black-screen@0.0.1
16 verbose cwd /home/ryan/local/black-screen
17 error Linux 3.19.0-32-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.2.0
20 error npm  v3.9.2
21 error code ELIFECYCLE
22 error black-screen@0.0.1 start: `npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron`
22 error Exit status 1
23 error Failed at the black-screen@0.0.1 start script 'npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the black-screen package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs black-screen
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls black-screen
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by davetoxa** [comment]
@rv816 because, currently only OS X is supported, please read [install section](https://github.com/shockone/black-screen#install)

**Comment by dmitriyBabenko** [comment]
@rv816 Try something like:
`npm run compile`
`npm i -g electron-packager`
`electron-packager . "$npm_package_productName" --overwrite --platform=linux --arch=x64 --version=$npm_package_electronVersion --out='ReleaseLinux' --icon='./icon.png'`
Work on Ubuntu 16.04.
