### ISSUE TITLE
Not installing on MacOS

### ISSUE THREAD

**Issue by erikpragt-siteminder** [shockone/black-screen#369]
After running `npm i`, I get the following errors:

```
> black-screen@0.0.1 preinstall /Users/erikpragt/projects/other/black-screen
> npm prune


> black-screen@0.0.1 postinstall /Users/erikpragt/projects/other/black-screen
> npm run recompile


> black-screen@0.0.1 recompile /Users/erikpragt/projects/other/black-screen
> export ELECTRON_VERSION=$(npm run electron-version --silent); HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$ELECTRON_VERSION --arch=x64 --dist-url=https://atom.io/download/atom-shell

gyp ERR! configure error
gyp ERR! stack Error: Invalid version number: 1.1.1
gyp ERR! stack     at getNodeDir (/Users/erikpragt/projects/other/black-screen/node_modules/npm/node_modules/node-gyp/lib/configure.js:69:25)
gyp ERR! stack     at /Users/erikpragt/projects/other/black-screen/node_modules/npm/node_modules/node-gyp/lib/configure.js:41:7
gyp ERR! stack     at /Users/erikpragt/projects/other/black-screen/node_modules/npm/node_modules/node-gyp/lib/configure.js:393:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/6.2.0/bin/node" "/Users/erikpragt/projects/other/black-screen/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--target=\u001b[m\u001b[K1.1.1" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /Users/erikpragt/projects/other/black-screen/node_modules/pty.js
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/Users/erikpragt/projects/other/black-screen/node_modules/.bin/npm" "run" "recompile"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 recompile: `export ELECTRON_VERSION=$(npm run electron-version --silent); HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$ELECTRON_VERSION --arch=x64 --dist-url=https://atom.io/download/atom-shell`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 recompile script 'export ELECTRON_VERSION=$(npm run electron-version --silent); HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$ELECTRON_VERSION --arch=x64 --dist-url=https://atom.io/download/atom-shell'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     export ELECTRON_VERSION=$(npm run electron-version --silent); HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$ELECTRON_VERSION --arch=x64 --dist-url=https://atom.io/download/atom-shell
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erikpragt/projects/other/black-screen/npm-debug.log

npm WARN tslint@3.10.2 requires a peer of typescript@>=1.7.3 but none was installed.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 postinstall: `npm run recompile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 postinstall script 'npm run recompile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run recompile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.
```

**Comment by ArmandBiteau** [comment]
Updating to the last Node release (online package 6.2) saved my life !
