### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by MaxNoe** [shockone/black-screen#399]
Running node v6.2.0 on xenial, I get 

```
$ npm i
> nslog@3.0.0 install /home/max/.local/black-screen/node_modules/nslog
> node-gyp rebuild

make: Entering directory '/home/max/.local/black-screen/node_modules/nslog/build'
  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_linux.o
  SOLINK_MODULE(target) Release/obj.target/nslog.node
  COPY Release/nslog.node
make: Leaving directory '/home/max/.local/black-screen/node_modules/nslog/build'

> black-screen@0.0.1 preinstall /home/max/.local/black-screen
> npm prune


> black-screen@0.0.1 postinstall /home/max/.local/black-screen
> npm run recompile


> black-screen@0.0.1 recompile /home/max/.local/black-screen
> export ELECTRON_VERSION=$(npm run electron-version --silent); HOME=~/.electron-gyp cd node_modules/pty.js; node-gyp rebuild --target=$ELECTRON_VERSION --arch=x64 --dist-url=https://atom.io/download/atom-shell

make: Entering directory '/home/max/.local/black-screen/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:222:34: warning: ignoring return value of ‘int chdir(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
       if (strlen(cwd)) chdir(cwd);
                                  ^
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/home/max/.local/black-screen/node_modules/pty.js/build'
black-screen@0.0.1 /home/max/.local/black-screen
├─┬ electron-rebuild@1.1.4 
│ ├── glob@6.0.4 
│ ├── lodash@3.10.1 
│ └── nslog@3.0.0 
└── UNMET PEER DEPENDENCY typescript@1.9.0-dev.20160514

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN tslint@3.10.2 requires a peer of typescript@>=1.7.3 but none was installed.
```

And 
```
$ npm start
> black-screen@0.0.1 start /home/max/.local/black-screen
> npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron


> black-screen@0.0.1 compile /home/max/.local/black-screen
> npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html


> black-screen@0.0.1 cleanup /home/max/.local/black-screen
> rm -rf compiled


> black-screen@0.0.1 compile-tsc /home/max/.local/black-screen
> tsc


> black-screen@0.0.1 compile-scss /home/max/.local/black-screen
> node-sass stylesheets/main.scss compiled/all.css > /dev/tty

fs.js:945
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/home/max/.local/black-screen/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.getInstalledBinaries (/home/max/.local/black-screen/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/home/max/.local/black-screen/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/max/.local/black-screen/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/max/.local/black-screen/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/home/max/.local/black-screen/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/max/.local/nodejs-v6.2.0/bin/node" "/home/max/.local/black-screen/node_modules/.bin/npm" "run" "compile-scss"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 compile-scss: `node-sass stylesheets/main.scss compiled/all.css > /dev/tty`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 compile-scss script 'node-sass stylesheets/main.scss compiled/all.css > /dev/tty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass stylesheets/main.scss compiled/all.css > /dev/tty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/.local/black-screen/npm-debug.log

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/max/.local/nodejs-v6.2.0/bin/node" "/home/max/.local/black-screen/node_modules/.bin/npm" "run" "compile"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 compile: `npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 compile script 'npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/.local/black-screen/npm-debug.log

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/max/.local/nodejs-v6.2.0/bin/node" "/home/max/.local/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 start: `npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 start script 'npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/.local/black-screen/npm-debug.log
```

This is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/max/.local/nodejs-v6.2.0/bin/node',
1 verbose cli   '/home/max/.local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle black-screen@0.0.1~prestart: black-screen@0.0.1
6 silly lifecycle black-screen@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle black-screen@0.0.1~start: black-screen@0.0.1
8 verbose lifecycle black-screen@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle black-screen@0.0.1~start: PATH: /home/max/.local/nodejs-v6.2.0/lib/node_modules/npm/bin/node-gyp-bin:/home/max/.local/black-screen/node_modules/.bin:/home/max/.local/nodejs-v6.2.0/bin:/home/max/.local/bin:/home/max/Software/scripts:/home/max/Software/anaconda3/bin:/home/max/Software/Telegram/:/home/max/Software/texlive/2015/bin/x86_64-linux:/home/max/Software/root6-python3/bin:/home/max/Software/TRUEE/bin/:/home/max/Software/scripts:/home/max/Software/anaconda3/bin:/home/max/Software/Telegram/:/home/max/Software/texlive/2015/bin/x86_64-linux:/home/max/Software/TRUEE/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle black-screen@0.0.1~start: CWD: /home/max/.local/black-screen
11 silly lifecycle black-screen@0.0.1~start: Args: [ '-c',
11 silly lifecycle   'npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron' ]
12 silly lifecycle black-screen@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle black-screen@0.0.1~start: Failed to exec start script
14 verbose stack Error: black-screen@0.0.1 start: `npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/max/.local/nodejs-v6.2.0/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/max/.local/nodejs-v6.2.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid black-screen@0.0.1
16 verbose cwd /home/max/.local/black-screen
17 error Linux 4.4.0-22-generic
18 error argv "/home/max/.local/nodejs-v6.2.0/bin/node" "/home/max/.local/bin/npm" "start"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error black-screen@0.0.1 start: `npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron`
22 error Exit status 1
23 error Failed at the black-screen@0.0.1 start script 'npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the black-screen package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs black-screen
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls black-screen
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by shockone** [comment]
Can you remove node_modules and install them again?

**Comment by MaxNoe** [comment]
Now I get:

```
$ npm start

> black-screen@0.0.1 start /home/max/.local/black-screen
> npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron


> black-screen@0.0.1 compile /home/max/.local/black-screen
> npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html


> black-screen@0.0.1 cleanup /home/max/.local/black-screen
> rm -rf compiled


> black-screen@0.0.1 compile-tsc /home/max/.local/black-screen
> tsc


> black-screen@0.0.1 compile-scss /home/max/.local/black-screen
> node-sass stylesheets/main.scss compiled/all.css > /dev/tty

Rendering Complete, saving .css file...
Wrote CSS to /home/max/.local/black-screen/compiled/all.css

> black-screen@0.0.1 copy-html /home/max/.local/black-screen
> cp src/views/index.html compiled/src/views > /dev/tty

cp: cannot create regular file 'compiled/src/views': No such file or directory

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/max/.local/nodejs-v6.2.0/bin/node" "/home/max/.local/black-screen/node_modules/.bin/npm" "run" "copy-html"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 copy-html: `cp src/views/index.html compiled/src/views > /dev/tty`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 copy-html script 'cp src/views/index.html compiled/src/views > /dev/tty'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cp src/views/index.html compiled/src/views > /dev/tty
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/.local/black-screen/npm-debug.log

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/max/.local/nodejs-v6.2.0/bin/node" "/home/max/.local/black-screen/node_modules/.bin/npm" "run" "compile"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 compile: `npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 compile script 'npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run cleanup && npm run compile-tsc && npm run compile-scss && npm run copy-html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/.local/black-screen/npm-debug.log

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/max/.local/nodejs-v6.2.0/bin/node" "/home/max/.local/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 start: `npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.0.1 start script 'npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile && npm run watch-tsc | npm run watch-scss | npm run electron
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/max/.local/black-screen/npm-debug.log
```

**Comment by shockone** [comment]
Fixed.
