### ISSUE TITLE
cd does not work

### ISSUE THREAD

**Issue by quarterto** [shockone/black-screen#462]
Running `cd` does nothing. There is no output in the console. I've tested this on 0.0.34 and latest master.

**Comment by vinnymac** [comment]
`cd` appears to work for me. I do not see any console output, but directories have changed if I check with `ls`. What is your OS version? Did you install using `brew cask install black-screen`?

**Comment by aequasi** [comment]
Can confirm that a new install of black-screen (via brew cask install) on `El Capitan 10.11.5`, that `cd` does not work on the latest version.

**Comment by Jarred-Sumner** [comment]
`cd` is working on the latest version installed via `brew cask` for me on:

![image](https://cloud.githubusercontent.com/assets/709451/15912287/347f21f6-2d88-11e6-887b-6147ebb443e1.png)

**Comment by shockone** [comment]
@quarterto there is current directory on the left side of the bottom panel. Does it change when you cd?

**Comment by quarterto** [comment]
No.

**Comment by shockone** [comment]
Please click on the smiley below, if you experience the same issue.

**Comment by viktomas** [comment]
I had the same issue. Can you guys run `alias cd` in your command line? If you you for example have `alias cd="nocorrect cd"` `black-screen` will use this alias to expand your prompt input.

But after that it gets lost because `cd` expands to `nocorrect cd` and `black-screen` doesn't know `nocorrect` command. Quick solution is to remove this alias from your config files.

Long lasting solution is to let PTY do it's job with cd and then parse the new folder from it. @shockone I don't know if that's possible, but it would prevent all these types of issues in the future.

**Comment by shockone** [comment]
@viktomas how to parse shell session environment and not to lose the return status of the executed command?

For example, I execute `cd foo; false` and want to know both the new PWD and that `$?` is 1.

**Comment by viktomas** [comment]
@shockone: Understand. I'll try to have a look how the `$PROMPT_COMMAND` in `zsh` works. I don't think it's going to be an easy issue to solve and I'm not even sure that `pty.js` will provide all the interface we need.

**Comment by shockone** [comment]
@viktomas it's not the same as in `$PROMPT_COMMAND`. A shell preserves the same session between jobs, but we create a new one every time in order to know when a previous job ended.

**Comment by steelbrain** [comment]
Hey I'm also experiencing this issue
I didn't know what to include in the debug info but I hope this picture will do
<img src="https://cloud.githubusercontent.com/assets/4278113/16657782/8e57cd94-4418-11e6-8304-c698f2ff2bda.png">

**Comment by sebastianpicklum** [comment]
Same here on OSX 10.11.6 (15G31). Thought first it might be an Issue with zsh, but the same happens with bash as well.

**Comment by sei0o** [comment]
Same here with zsh. I'm using macOS Sierra(10.12) Beta (16A201w).

**Comment by sebastianpicklum** [comment]
I digged a little deeper and found following error message (funnily I don’t use rvm)

`fs.js:1578 Uncaught (in promise) Error: ENOENT: no such file or directory, realpath '/Users/MYUSER/.rvm/rubies/default'
    at Error (native)
    at Object.realpathSync (fs.js:1578:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:303:29)
    at /Applications/Black Screen.app/Contents/Resources/app.asar/compiled/src/plugins/RVM.js:23:23
    at next (native)
    at fulfilled (/Applications/Black Screen.app/Contents/Resources/app.asar/compiled/src/plugins/RVM.js:4:58)`

**Comment by leothelocust** [comment]
Where are we at on this? I'm getting the same problem. @shockone

**Comment by shockone** [comment]
**The workaround** is to remove the `cd='nocorrect cd'` alias from your shell config.

**Comment by yqrashawn** [comment]
<img width="568" alt="screen shot 2017-10-30 at 1 54 42 pm" src="https://user-images.githubusercontent.com/15090582/32156702-fcba0586-bd0c-11e7-8019-a1b5301c50ad.png">

Seems like it's the same problem. `fasd_cd` is a function defined in prezto https://github.com/sorin-ionescu/prezto/blob/master/modules/fasd/init.zsh#L40      
it works fine in zsh with iterm.
