### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by stowball** [shockone/black-screen#492]
When performing the development setup steps

```sh
git clone https://github.com/shockone/black-screen.git && cd black-screen
npm start
```

it fails with this error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart black-screen@0.0.37
6 verbose unsafe-perm in lifecycle true
7 info black-screen@0.0.37 Failed to exec prestart script
8 verbose stack Error: black-screen@0.0.37 prestart: `npm install && npm run compile`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at EventEmitter.emit (events.js:172:7)
8 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at ChildProcess.emit (events.js:172:7)
8 verbose stack     at maybeClose (internal/child_process.js:821:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose pkgid black-screen@0.0.37
10 verbose cwd /Users/stowball/Documents/Git/black-screen
11 error Darwin 15.5.0
12 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
13 error node v4.3.1
14 error npm  v2.14.12
15 error code ELIFECYCLE
16 error black-screen@0.0.37 prestart: `npm install && npm run compile`
16 error Exit status 1
17 error Failed at the black-screen@0.0.37 prestart script 'npm install && npm run compile'.
17 error This is most likely a problem with the black-screen package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm install && npm run compile
17 error You can get their info via:
17 error     npm owner ls black-screen
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
```

MacBook Pro - 10.11.5

**Comment by shockone** [comment]
Please update your node version to 6.2.0
